name: ReturnNames

description: 'Take info from repo and make useable names from it.'

inputs:
  RepoPath: 
    description: 'Repo info'
    required: true
    default: "${{ github.repository }}"
  Tag: 
    description: 'Tag info'
    required: true
    default: "${{ github.ref }}"

#outputs:
#  RepoName: 
#    description: 'Name of the Repo'
#    value: "${{ steps.RepoName.outputs._1 }}"

runs:
  using: "composite"

  steps:
  - uses: actions/checkout@v3
  
  - name: GetSplit - Repo
    uses: rishabhgupta/split-by@v1
    id: RepoName
    with:
      string: "${{ inputs.RepoPath }}"
      split-by: "/"

  - name: GetSplit - Tag
    uses: rishabhgupta/split-by@v1
    id: TagName
    with:
      string: "${{ inputs.Tag }}"
      split-by: "/"

  - name: Upload Artifact    
    uses: actions/upload-artifact@v2
    with:
      name: "${{ steps.RepoName.outputs._1 }} - ${{ steps.TagName.outputs._2  }}"
      path: "${{ github.workspace }}/Module/**"
  
  - uses: ncipollo/release-action@v1
    with:
      artifacts: "${{ github.workspace }}/Module/**${{ steps.RepoName.outputs._1 }} - ${{ steps.TagName.outputs._2  }}"

