name: ReturnNames

description: 'Take info from repo and make useable names from it.'

inputs:
  Filename: 
    description: 'Name of the ZipFile'
    required: true
    default: 'Test'

#outputs:
#  RepoName: 
#    description: 'Name of the Repo'
#    value: "${{ steps.RepoName.outputs._1 }}"

runs:
  using: "composite"

  steps:
  - uses: actions/checkout@v3

  - name: Archive Release
    uses: thedoctor0/zip-release@master
    with:
      filename: ".github/${{ inputs.Filename }}"
      path: "./Module/"
      exclusions: '*.git* .env .github/Workflows/*'

  - name: Upload Artifact    
    uses: actions/upload-artifact@v2
    with:
      name: "${{ inputs.Filename }}"
      path: "${{ github.workspace }}/.github"


# - uses: ncipollo/release-action
